[build]
  publish = "." 
  functions = "netlify/functions"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/html/*"
  to = "/index.html"
  status = 200
