name: Quest Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04 # Menggunakan Ubuntu 24.04 yang akan datang

    steps:
      # 1. Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3 # Update ke versi terbaru v3

      # 2. Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3 # Update ke versi terbaru v3
        with:
          node-version: '18'

      # 3. Cache Node.js modules to speed up future builds
      - name: Cache Node.js modules
        uses: actions/cache@v3 # Update ke v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # 4. Install dependencies (including npm packages)
      - name: Install dependencies
        run: npm install

      # 5. Build the project (prepare production files)
      - name: Build project
        run: npm run build

      # 6. Run Airtable script with API credentials
      - name: Run Airtable script with API credentials
        run: |
          node js/airtable.js
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}

      # 7. Run tests (optional, can be customized based on your testing framework)
      - name: Run tests
        run: npm test
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}

      # 8. Install Netlify CLI
      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      # 9. Deploy to Netlify (clear cache to avoid outdated content)
      - name: Deploy to Netlify
        run: |
          netlify deploy --prod --dir=dist --clear-cache # Clear cache to avoid outdated content
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}

      # 10. Cache build output to speed up future builds
      - name: Cache build output
        uses: actions/cache@v3
        with:
          path: dist/
          key: ${{ runner.os }}-dist-${{ hashFiles('**/dist/*') }}
          restore-keys: |
            ${{ runner.os }}-dist-

      # 11. Optional step to notify deployment success/failure (e.g., Slack, Email)
      - name: Notify deployment status (optional)
        if: success()
        run: echo "Deployment to Netlify successful!"
        # Optionally, add integrations like Slack, email, etc. for notifications.

